# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 856773ed7eb8b91bebffd56d9caef2ac929aefc7c7f6b191000d4295d0ce73a3fa27106958f8ca4fdd1a000aaaf1a034857afedb68de0f73771347932bf9cd98

test:
  secret_key_base: 5be01e9afd4dfce51a9cbbbeca5afe3b575b4f0ae942cd649439ccc272aaceb310dc2223c95c6b579d493caca8f32f4f2b09a363fbae1f8e233686c1e11be840

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
